---
title: "[BUG] Admin login uses hardcoded fallback credentials"
labels:
  - bug
  - needs-triage
---
## Summary
If environment variables are missing, the admin login defaults to `admin@wedding.com / admin123`, creating a serious security vulnerability.

## Steps to Reproduce
1. Start the application without admin credentials in env.
2. Attempt to log in using the default credentials.

## Expected Behavior
Admin authentication should require configured credentials stored securely in the database.

## Actual Behavior
Fallback credentials allow unintended access.

## Proposed Solution
1. Create an admin user in the database with hashed password and `ADMIN` role.
2. Update `lib/auth.ts` to authenticate against the database only.
3. Remove hardcoded fallback and document setup steps.

## Priority
Critical security fix.
