---
title: "[BUG] RSVP and contact forms crash without email credentials"
labels:
  - bug
  - needs-triage
---
## Summary
RSVP and contact API routes fail with 500 errors when `GMAIL_USER` and `GMAIL_APP_PASSWORD` are not configured, exposing stack traces and blocking submissions.

## Steps to Reproduce
1. Deploy or run the app without email environment variables.
2. Submit the RSVP or contact form.

## Expected Behavior
Forms should gracefully notify the user that email service is unavailable and avoid server errors.

## Actual Behavior
Server responds with HTTP 500 and a logged "Missing API key" warning.

## Proposed Solution
1. In `client/src/lib/email.ts`, detect missing env vars and throw a controlled error.
2. Update `client/src/app/api/rsvp/submit/route.ts` and `client/src/app/api/contact/route.ts` to return a 400/503 with a friendly message.
3. Document required variables in `.env.example` and README.

## Priority
Critical for production stability.
